version: '3.8'
services:
  webserver:
    build: ./
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
  db:
    image: mysql
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: laravel_db_1
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123123
      MYSQL_ROOT_PASSWORD: 123123
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 123123
volumes:
  persistent: